Fixed get_weil_polys.
isogeny-primes/isogeny-primes pull request #17
Opened 2021-04-10 07:38 UTC by koffie

This solves #16 

Note that before this commit we have
```
F = GF(7^3)
%time weil_polys = get_weil_polys(F)
```
gives:
```
CPU times: user 1min 56s, sys: 719 ms, total: 1min 57s
Wall time: 1min 57s
```
while after this commit we have:
```
CPU times: user 1.13 ms, sys: 0 ns, total: 1.13 ms
Wall time: 1.14 ms
```
so we also have the much wanted speedup.

With this enhancement we might want to make "loop_curves" the default.

2021-04-10 19:53 UTC, koffie commented
Hi @BarinderBanwait , when you merge this commit could you do a squash and merge so that the last two silly commits won't stay in the history of the project forever.

2021-04-12 09:47 UTC, BarinderBanwait requested changes
Looks good ... I would suggest that the `q` be replaced with `p` throughout since then it corresponds exactly to Waterhouse Theorem 4.1.

2021-04-12 09:47 UTC, BarinderBanwait commented on isogeny_primes.py
> +    R = PolynomialRing(QQ,'x')
This is already defined as a global, since loads of methods need it, so it should be removed here.

2021-04-19 05:46 UTC, BarinderBanwait approved these changes
Looks good, will merge!

2021-04-19 05:47 UTC, merged